package com.vibeplayer.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light color scheme (static fallback inspired by the QT app's light palette)
val LightPrimary = Color(0xFF2E6259)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB2F0E2)
val LightOnPrimaryContainer = Color(0xFF00201B)
val LightSecondary = Color(0xFF4B635D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFAFDFB)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFFAFDFB)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceVariant = Color(0xFFDCE4E0)
val LightOnSurfaceVariant = Color(0xFF404946)
val LightSurfaceContainerLow = Color(0xFFF4F7F5)
val LightSurfaceContainer = Color(0xFFEEF2EF)
val LightSurfaceContainerHigh = Color(0xFFE8EDEA)
val LightSurfaceContainerHighest = Color(0xFFE2E7E4)

// Dark color scheme (static fallback inspired by the QT app's dark palette)
val DarkPrimary = Color(0xFF97D4C6)
val DarkOnPrimary = Color(0xFF003730)
val DarkPrimaryContainer = Color(0xFF155046)
val DarkOnPrimaryContainer = Color(0xFFB2F0E2)
val DarkSecondary = Color(0xFFB2CCC5)
val DarkOnSecondary = Color(0xFF1D352F)
val DarkBackground = Color(0xFF0F1217)
val DarkOnBackground = Color(0xFFE0E3E1)
val DarkSurface = Color(0xFF171C22)
val DarkOnSurface = Color(0xFFE0E3E1)
val DarkSurfaceVariant = Color(0xFF3F4946)
val DarkOnSurfaceVariant = Color(0xFFBEC9C5)
val DarkSurfaceContainerLow = Color(0xFF151A20)
val DarkSurfaceContainer = Color(0xFF1B2127)
val DarkSurfaceContainerHigh = Color(0xFF21272E)
val DarkSurfaceContainerHighest = Color(0xFF2A3139)
